project:
  type: website
  output-dir: docs
  render: 
    - "/posts/*"
    - "*.qmd"

website:
  title: "Yuki Iwanaga"
  google-analytics: "G-G4BZMT89L0"
  image: "assets/images/network_icon_square_minty.png"                       # Default site thumbnail image for twitter /open-graph
  favicon: "assets/images/network_icon_square_minty.png"                     # The favicon for your site provides an icon for browser tabs and other sites that link to yours.
  site-url: https://nagayu71.github.io/
  twitter-card: true
  open-graph: true
  navbar:
    # logo: "assets/images/icon.png"
    right:
      - text: "Home"
        href: index.qmd
      # - text: "Research"
      #   href: research.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Links"
        # menu: 
        #   - text: "Zenn"
        #     href: https://zenn.dev/nagayu71
        #   - text: "Qiita"
        #     href: https://qiita.com/Nagayu71
        href: links.qmd
    tools:
      - icon: github
        href: https://github.com/Nagayu71
    collapse: true                                    # Collapse the navbar into a menu when the display becomes narrow.
  search: 
    keyboard-shortcut: ["?", "H"]
  page-navigation: true
  back-to-top-navigation: true
  page-footer: 
    left: "Built with [Quarto](https://quarto.org/)"
    center: 
      - text: "© 2024, Yuki Iwanaga"
        href: terms.qmd
    right: 
      - icon: github
        href: https://github.com/Nagayu71
      - icon: envelope
        href: mailto:yuki.iwanaga136@gmail.com
    background: "#78C2AD"

format:
  html:
    mainfont: "BIZ UDPGothic"  # 教育やビジネス文書作成などに活用できるよう、より多くの方にとって読みやすく使いやすいように設計されたユニバーサルデザインフォント
    theme: 
      light: minty
      # dark: darkly
    css: styles/styles.css
    code-block-bg: true
    code-block-border-left: "#7CC4AC" # see https://quarto.org/docs/output-formats/html-code.html#appearance
    highlight-style: ayu # see https://quarto.org/docs/output-formats/html-code.html#highlighting
    toc: true
    toc-expand: 2
    toc-depth: 4
    toc-title: "目次"
    abstract-title: "概要"
    number-sections: false
    html-math-method: mathjax # katex だと長い数式の横スクロールができなくなる
    # lang: ja
    link-external-newwindow: true
    include-in-header: 
      - styles/font.html  # ウェブフォントの利用．どのデバイスでも同じフォントを使える．
      - text: |           # ナビゲーションバーのフォントを大きめにする
          <style>
          .menu-text {
            font-size: 120%;
          }
          </style>

crossref: 
  eq-prefix: 式
  def-prefix: 定義
  def-title: 定義
  thm-prefix: 定理
  thm-title: 定理
  fig-prefix: 図
  fig-title: 図
  sec-prefix: §
  lst-prefix: Code
  lst-title: Code
# date-format: "M/DD/YYYY"

execute: 
  freeze: auto # see https://quarto.org/docs/projects/code-execution.html#freeze
