---
title: "Research"
title-block-banner: true
page-layout: full
number-sections: false
toc: false
---

## About

My research interests lie at the intersection of economics and network science. Although network science is a relatively new field that emerged in the years around the early 2000s, it has been applied across various domains with significant success. In economics, considering network structures has provided deeper insights in research areas such as input-output analysis, cascading failures in financial networks, and measuring peer effects.

The focus of my research is to develop a statistical model that identifies the mechanisms behind the formation of observed economic and social networks. A key concept in economic model building is microfoundation, and I am currently working on a model based on network game theory.

## Preprints

- Welfare bounds for linear-quadratic network games [[Incl. Online Appendix](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5706124)] [[code](https://github.com/Nagayu71/lqng-welfare-bounds)]  
  Yuki Iwanaga, Teruyoshi Kobayashi  
  DOI: [10.2139/ssrn.5706124](https://dx.doi.org/10.2139/ssrn.5706124)

## Presentation

#### in English

1. Iwanaga and Kobayashi. Network Game Meets Machine Learning: A Microfounded Graphical Lasso. [The 10th Annual International Conference in Hawaiʻi](https://www.econ.kobe-u.ac.jp/news/18216/). 2025/9/30.

#### in Japanese

1. TBA. [Nonlinear Physics Laboratory, Kyushu U](https://sites.google.com/view/nonlinear-kyushu-univ/). 2025/12/18.
2. TBA. [ネットワーク科学研究会2025](https://www.network-science-seminar.com/top). 2026/2/18.